# Generated by Django 3.0.3 on 2021-12-21 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='customer_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_login'),
        ),
    ]
