# Generated by Django 3.0.3 on 2021-12-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211221_0951'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer_login',
            managers=[
            ],
        ),
    ]
