# Generated by Django 3.0.3 on 2021-12-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20211221_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
