# Generated by Django 3.0.3 on 2021-12-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_cart_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='customer_details',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_login'),
        ),
    ]
