# Generated by Django 3.0.3 on 2021-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_login',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
