# Generated by Django 3.0.3 on 2021-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20211221_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_number', models.IntegerField()),
            ],
        ),
    ]
