# Generated by Django 3.0.3 on 2021-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='food_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
