# Generated by Django 3.2.7 on 2021-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
